/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/brainBothFeetComp.glb");
  const { actions } = useAnimations(animations, group);

  useFrame(() => {
    group.current.rotation.y = -90;
    group.current.position.y = 0;
    group.current.position.z = -3.5;
  });

  useEffect(() => {
    actions.BrainAction.play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Brain" rotation={[Math.PI / 2, 0, 0]} scale={1.66}>
        <mesh
          geometry={nodes.Left.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Right.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/brainBothFeetComp.glb");
