/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/brainCompV1.glb");
  const { actions } = useAnimations(animations, group);

  useFrame(() => {
    group.current.position.y = 0;
    group.current.position.z = -3.5;
    group.current.rotation.y += 0.01;
  });

  useEffect(() => {
    console.log(actions);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.66}>
        <mesh
          geometry={nodes.Brain_Part_01.geometry}
          material={nodes.Brain_Part_01.material}
        />
        <mesh
          geometry={nodes.Brain_Part_02.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Brain_Part_03.geometry}
          material={nodes.Brain_Part_03.material}
        />
        <mesh
          geometry={nodes.Brain_Part_04.geometry}
          material={nodes.Brain_Part_04.material}
        />
        <mesh
          geometry={nodes.Brain_Part_05.geometry}
          material={nodes.Brain_Part_05.material}
        />
        <mesh
          geometry={nodes.Brain_Part_06.geometry}
          material={nodes.Brain_Part_06.material}
        />
      </group>
      {/* <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        scale={36.46}
      /> */}
    </group>
  );
}

useGLTF.preload("/brainCompV1.glb");
